### ISSUE TITLE
I turned ad blocker on but not detected

### ISSUE THREAD

**Issue by bacloud22** [digitalfortress-tech/ad-rotator#16]
First let me thank you for this very useful library !!!

now, Still the error:

> No Adblocker detected. 

Firefox 97.0.1 (64 bits) on Windows server 2019
AdAvoid@AdBlockerUltimate Version: 3.7.15

**Comment by niketpathak** [comment]
Hello there,

Thank you for reporting the issue. However, it seems to not be reproducible for me. 

Here is a screenshot (Tested on Firefox 97, AdBlockerUltimate)
![image](https://user-images.githubusercontent.com/10226768/155962802-67335ad9-fa3b-41d6-8a53-08bc73086c45.png)

I also created a [JS fiddle](https://jsfiddle.net/niketpathak/u8bkvyn6/) for you to test it again. Please try to reproduce the bug on JSfiddle so it will be easier for me to find an error (if it really exists). 

Thank you.

**Comment by bacloud22** [comment]
![Capture](https://user-images.githubusercontent.com/10267332/155965484-e99dc4da-26d9-4d08-b35a-f3f72d93b86c.PNG)
Site is scrambled, nearly all assets are being blocked by the extension !!!

**Comment by niketpathak** [comment]
okay. that's super weird. Even the `favicon.ico` seems to be blocked which should definitely not happen! When I open the website, it works for me. And so does the jsfiddle. Unable to reproduce the issue.

**Comment by bacloud22** [comment]
Let me check when I get back home 🏘️😊

**Comment by bacloud22** [comment]
![Capture](https://user-images.githubusercontent.com/10267332/156028379-c0cd83d7-18b2-4360-8b26-b7d5d8b7c72d.PNG)

**Comment by niketpathak** [comment]
Ah see, there's something totally funny going on there. As per the image you posted, even if Ad-rotator doesn't work, at least the html (more precisely, the text within it) should be seen, and that is not the case for you.

Also, check out this screencast (I am just not able to reproduce the issue that you have and so, its not really possible to provide a fix)

https://user-images.githubusercontent.com/10226768/156371378-5833136f-f756-4151-abe1-1db76d1110aa.mp4

**Comment by bacloud22** [comment]
ok good luck.

**Comment by niketpathak** [comment]
Thanks to you too! Good luck with your project :+1:
